// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-_LsfXbuasmyzD6by7BtcXlepXrRCsY',
    appId: '1:259679551913:web:cf34af88f3c6fdc9db44b8',
    messagingSenderId: '259679551913',
    projectId: 'flutter-bonus-assignment',
    authDomain: 'flutter-bonus-assignment.firebaseapp.com',
    storageBucket: 'flutter-bonus-assignment.firebasestorage.app',
    measurementId: 'G-5ZG8MV8XSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsiz8v5mvist_k5UnJlyBxUR1_jCxXic',
    appId: '1:259679551913:android:691e27397b9c6858db44b8',
    messagingSenderId: '259679551913',
    projectId: 'flutter-bonus-assignment',
    storageBucket: 'flutter-bonus-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3KkGE0VDomzRA5EBuKm9_DCeoBwtiXRA',
    appId: '1:259679551913:ios:278ae3e002f08beddb44b8',
    messagingSenderId: '259679551913',
    projectId: 'flutter-bonus-assignment',
    storageBucket: 'flutter-bonus-assignment.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3KkGE0VDomzRA5EBuKm9_DCeoBwtiXRA',
    appId: '1:259679551913:ios:278ae3e002f08beddb44b8',
    messagingSenderId: '259679551913',
    projectId: 'flutter-bonus-assignment',
    storageBucket: 'flutter-bonus-assignment.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy-_LsfXbuasmyzD6by7BtcXlepXrRCsY',
    appId: '1:259679551913:web:ee59b5cd07fd1e2adb44b8',
    messagingSenderId: '259679551913',
    projectId: 'flutter-bonus-assignment',
    authDomain: 'flutter-bonus-assignment.firebaseapp.com',
    storageBucket: 'flutter-bonus-assignment.firebasestorage.app',
    measurementId: 'G-FPH5G6767B',
  );
}